json-parser:
  class: \Night\Component\FileParser\JSONParser
symfony-yaml:
  class: \Symfony\Component\Yaml\Yaml
  public: false
yaml-parser:
  class: \Night\Component\FileParser\YAMLParser
  arguments:
    - @symfony-yaml
php-parser:
  class: \Night\Component\FileParser\PHPParser
smarty-templating:
  class: \Night\Component\Templating\SmartyTemplating
  arguments:
    - @yaml-parser
twig-templating:
  class: \Night\Component\Templating\TwigTemplating
  arguments:
    - @yaml-parser
pdo-repository:
  class: \Night\Component\Repository\PDORepository
  arguments:
    - @yaml-parser
pdo-repository-profiler:
  class: \Night\Component\Profiling\PDORepositoryProfiler
  tags:
    - profiler
  singleton: getInstance