json-parser:
  class: \Night\Component\FileParser\JSONParser
symfony-yaml:
  class: \Symfony\Component\Yaml\Yaml
  public: false
yaml-parser:
  class: \Night\Component\FileParser\YAMLParser
  arguments:
    - @symfony-yaml
php-parser:
  class: \Night\Component\FileParser\PHPParser
smarty-templating:
  class: \Night\Component\Templating\SmartyTemplating
  arguments:
    - @yaml-parser
twig-templating:
  class: \Night\Component\Templating\TwigTemplating
  arguments:
    - @yaml-parser
pdo-repository:
  class: \Night\Component\Repository\PDORepository
  arguments:
    - @yaml-parser
profiler:
  class: \Night\Component\Profiling\Profiler
  singleton: getInstance
pdo-repository-profiler:
  class: \Night\Component\Profiling\PDORepositoryProfiler
  tags:
    - profiler-component
  singleton: getInstance
routing-profiler:
  class: \Night\Component\Profiling\RoutingProfiler
  tags:
    - profiler-component
  singleton: getInstance
templating-profiler:
  class: \Night\Component\Profiling\TemplatingProfiler
  tags:
    - profiler-component
  singleton: getInstance
translator:
  class: \Night\Component\i18n\Translator
  arguments:
      - @yaml-parser
routing:
  class: \Night\Component\Routing\Routing
  arguments:
    - @yaml-parser